version: '3'
services:
  data-ingestion-service:
    build: ../..
    ports:
      - "8080:8080"
    #environment:
    #   - SPRING_PROFILES_ACTIVE=production
    #deploy:
    #  resources:
    #     limits:
    #       cpus: '1'
    #       memory: '512M'
    #restart: always
    healthcheck: # Healthcheck configuration
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s